name: Feature Request
description: Click this one to ask to add an feature!
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: You are a modder or a player?
      options:
        - Player.
        - Modder.
        - Both.
    validations:
      required: false
